apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: {{ template "zookeeper.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ with .Values.image }}{{ .repository }}{{ end }}
    tag: {{ with .Values.image }}{{ .tag }}{{ end }}
    pullPolicy: {{ with .Values.image }}{{ .pullPolicy }}{{ end }}
  persistence:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: {{ .Values.storage.className }}
    reclaimPolicy: Delete
    resources:
      requests:
        storage: {{ .Values.storage.cacheVolumeRequest }}
