apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: default
spec:
  # Add fields here
  replicas: 3
  image:
    repository: pravega/zookeeper
    tag: 0.2.7
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi
